services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
